version: '3.3'

services:
    stockpred:
        build: 
            context: .
            dockerfile: Dockerfile
        restart: always
        environment:
          NEVER_CRAWL: "false"
          RUN_PYMOO: "true"
          COMPRESS_AFTER_EXP: "true"
        volumes:
          - ./datasets:/code/datasets
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: '10'
                    memory: 60G
                reservations:
                    memory: 10G